//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Активности
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Активности()
        {
            this.Неодобренные_заявки = new HashSet<Неодобренные_заявки>();
            this.Одобренные_заявки = new HashSet<Одобренные_заявки>();
            this.Роли = new HashSet<Роли>();
        }
    
        public string Активность { get; set; }
        public Nullable<double> День { get; set; }
        public Nullable<System.TimeSpan> Время_начала { get; set; }
        public Nullable<int> id_Модератора { get; set; }
        public int id { get; set; }
        public Nullable<int> id_Мероприятия { get; set; }
    
        public virtual Мероприятия Мероприятия { get; set; }
        public virtual Модераторы Модераторы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Неодобренные_заявки> Неодобренные_заявки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Одобренные_заявки> Одобренные_заявки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Роли> Роли { get; set; }
    }
}
