//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Жюри
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Жюри()
        {
            this.Роли = new HashSet<Роли>();
        }
    
        public string ФИО { get; set; }
        public string пол { get; set; }
        public string почта { get; set; }
        public string дата_рождения { get; set; }
        public Nullable<int> страна { get; set; }
        public string телефон { get; set; }
        public string направление { get; set; }
        public string пароль { get; set; }
        public string фото { get; set; }
        public int id { get; set; }
    
        public virtual Страны Страны { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Роли> Роли { get; set; }
    }
}
