//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Одобренные_заявки
    {
        public int id { get; set; }
        public Nullable<int> id_Активности { get; set; }
        public Nullable<int> id_Модератора { get; set; }
        public Nullable<int> id_Организатора { get; set; }
        public Nullable<int> id_неодобренной_заявки { get; set; }
    
        public virtual Активности Активности { get; set; }
        public virtual Модераторы Модераторы { get; set; }
        public virtual Неодобренные_заявки Неодобренные_заявки { get; set; }
        public virtual Организаторы Организаторы { get; set; }
    }
}
