//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Организаторы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Организаторы()
        {
            this.Одобренные_заявки = new HashSet<Одобренные_заявки>();
        }
    
        public string ФИО { get; set; }
        public string Почта { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public Nullable<int> страна { get; set; }
        public string телефон { get; set; }
        public string пароль { get; set; }
        public string фото { get; set; }
        public string пол { get; set; }
        public int id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Одобренные_заявки> Одобренные_заявки { get; set; }
        public virtual Страны Страны { get; set; }
        public virtual Страны Страны1 { get; set; }
    }
}
