//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Роли
    {
        public int Роль { get; set; }
        public int id_Активности { get; set; }
        public int id_Жюри { get; set; }
        public int id { get; set; }
    
        public virtual Активности Активности { get; set; }
        public virtual Жюри Жюри { get; set; }
    }
}
